### ISSUE TITLE
FSP Fortron UPS Champ 1000 VA tower

### ISSUE THREAD

**Issue by virnik0** [networkupstools/nut-ddl#22]
I was unable to upload new DDL, so I put its content to my gist.

https://gist.github.com/virnik0/689e56d7b2a179260416aa5e5bb2063f

The UPS works with following configuration:
````
[ups2]
        desc = "FSP Fortron UPS Champ 1000 VA Tower (UPS2)"
        driver = "nutdrv_qx"
        port = "auto"
        vendorid = "0665"
        productid = "5161"
        product = "USB to Serial"
        vendor = "INNO TECH"
        pollinterval = 5
        limited_runtime_on_battery = disabled
        bypass_forbidding = enabled
        override.battery.runtime.low = 120
````
        
 The UPS doesn't report serial (well, reports zeroes), and ups.load is stuck on value of '0', making expected runtime unusable.
 
 Other than that, the UPS reports voltages both input, output, nominal... etc correctly along with the charge level and battery temperature.

**Comment by jimklimov** [comment]
Another recent report from mail:

````
Fortron UPS Champs.

upsc reports:

Init SSL without certificate database
battery.charge: 100
battery.voltage: 55.20
battery.voltage.high: 52.00
battery.voltage.low: 41.60
battery.voltage.nominal: 48.0
device.mfr:
device.model: WPHVT2K0
device.type: ups
[driver.name](http://driver.name/): blazer_usb
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/hidraw2
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.internal: 0.12
input.current.nominal: 8.0
input.frequency: 50.0
input.frequency.nominal: 50
input.voltage: 234.5
input.voltage.fault: 234.5
input.voltage.nominal: 230
output.voltage: 229.7
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: 01060.07
ups.load: 46
ups.mfr:
ups.model: WPHVT2K0
ups.productid: 5161
ups.status: OL
ups.temperature: 26.3
ups.type: online
ups.vendorid: 0665
````

**Comment by virnik0** [comment]
That is interesting. It reports load in your case. I tested blazer_usb, and report was also 0. UPS model and firmware are the same. Is it possible that load bellow 25% reads as 0% then? My approximate load on it is nearing 15% (it powers wireless backbone router, something like 48V/5A).

**Comment by jimklimov** [comment]
Poking these reports for DDL upload finally. Models are not the same (...1K... vs. ...2K...), but otherwise seems to be little difference in metadata. There seems to be a lot fewer data points in the second report however.
