### ISSUE TITLE
Best Power Patriot Pro 750

### ISSUE THREAD

**Issue by nursoda** [networkupstools/nut-ddl#4]
Opening issue as requested per http://lists.alioth.debian.org/pipermail/nut-upsuser/2015-November/010009.html to report values

UPS
   Manufacturer: Best Power, Model: Patriot Pro 750
   P/N: PP0750E S/N: 186PFA4126 REV: 00
Note: This is NOT a Patriot Pro II but just a Patriot Pro.

NUT
   2.7.2-4 (official debian jessie repos)

# upsc Best_Power_Patriot_Pro_750
Init SSL without certificate database
battery.charge: 100.0
battery.voltage: 27.5
battery.voltage.nominal: 24
device.mfr: Best Power
device.model: Patriot Pro 750
device.type: ups
driver.name: bestups
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/ttyS0
driver.version: 2.7.2
driver.version.internal: 1.06
input.frequency: 50.0
input.voltage: 233.0
input.voltage.nominal: 230
output.voltage: 233.0
output.voltage.nominal: 230
ups.load: 000
ups.mfr: Best Power
ups.model: Patriot Pro 750
ups.status: OL

# upsrw Best_Power_Patriot_Pro_750
<empty>

# upscmd -l Best_Power_Patriot_Pro_750
Instant commands supported on UPS [Best_Power_Patriot_Pro_750]:

test.battery.start - Start a battery test
test.battery.stop - Stop the battery test

**Comment by zykh** [comment]
Added, thanks!
